apiVersion: v1
kind: Service
metadata:
  name: xrfcapi
  namespace: xrf
spec:
  selector:
    app: xrfcapi
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrfc50
  namespace: xrf
  labels:
    app: xrfc50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrfc50
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-debug-sidecar: "true"
        linkerd.io/inject: enabled
      labels:
        app: xrfc50
    spec:
      containers:
      - name: xrfc
        image: tolgaomeratalay/xrfclient:3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_XRF
          value: "10.9.0.91"
        - name: XRF_PORT
          value: "9090"
