apiVersion: v1
kind: Service
metadata:
  name: xrfcapi
  namespace: xrf
spec:
  selector:
    app: xrfcapi
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrfc
  namespace: xrf
  labels:
    app: xrfc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrfc
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-debug-sidecar: "true"
        linkerd.io/inject: enabled
      labels:
        app: xrfc
    spec:
      containers:
      - name: xrfc
        image: tolgaomeratalay/xrfclient:1.0
        imagePullPolicy: IfNotPresent
